[Compatibility] Added CLIENT UNBLOCK command
microsoft/garnet pull request #886
Opened 2024-12-16 19:09 UTC by Vijay-Nirmal

Adding the CLIENT UNBLOCK command to garnet

- [x] Add CLIENT UNBLOCK commands
- [x] Add Integration Test cases and ACL Test
- [x] Add documentation

2025-01-07 22:13 UTC, TalZaccai requested changes
Thanks! Please see my comments.

2025-01-07 22:13 UTC, TalZaccai commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
What's the difference between this test and ClientUnblockBasicTest?

2025-01-07 22:13 UTC, TalZaccai commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
Can add a couple more tests here, for example - 
1 client blocks, send 1 force unblock and 1 add in parallel - check that either client gets the data or gets unblocked and data stays in collection, can repeat test multiple times.
Multiple clients blocking, multiple calls for force unblock & add in parallel - check that no added data gets lost (i.e. either stays in the collection or being returned to clients).

2025-01-12 19:06 UTC, Vijay-Nirmal commented on libs/server/Resp/ClientCommands.cs
> +                if (session.storeWrapper?.itemBroker is not null)
I am returning `0` instead of an error as is not possible to have blocked client when there is no `storeWrapper`

2025-01-12 19:08 UTC, Vijay-Nirmal commented on libs/server/Resp/ClientCommands.cs
> +                while (!RespWriteUtils.WriteInteger(1, ref dcurr, dend))
I have moved this inside the `if`, I think that should work as expected, because only why this like can execute `observer.CancellationTokenSource.Cancel()` or `observer.ResultFoundSemaphore.Release()` is called. If me know, If I understood it wrongly.

2025-01-12 19:11 UTC, Vijay-Nirmal commented on libs/server/Objects/ItemBroker/CollectionItemBroker.cs
> +            catch (OperationCanceledException) when (observer.CancellationTokenSource.IsCancellationRequested)
That should cause any issue right? earlier its just an empty catch, Now I am assigning a bool. Do you see any issue with that?

2025-01-12 19:27 UTC, Vijay-Nirmal commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
The only difference is that in ClientUnblockMultipleAttemptsTest I will try to unblock again and check the response, I will combine it.

2025-01-12 19:59 UTC, Vijay-Nirmal commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
Added a test concurrency, everything is working as expected. One finding is that, there could be multiple clients get the response as `1` if they are unblocking the same client. I would say it's expected as there is no point in having transactions for unblocking client ID

2025-01-13 19:58 UTC, Vijay-Nirmal commented
Fixed the review commands

2025-01-16 22:02 UTC, TalZaccai commented on libs/server/Resp/ClientCommands.cs
> +                while (!RespWriteUtils.WriteInteger(1, ref dcurr, dend))
You can still have a context switch happen here. What you need to do is have something similar to observer.HandleSetResult (say, observer.TryForceUnblock) that locks the ObserverStatusLock, and returns a boolean that indicates if the observer was force unblocked or not.

2025-01-16 22:04 UTC, TalZaccai commented on libs/server/Objects/ItemBroker/CollectionItemBroker.cs
> +            catch (OperationCanceledException) when (observer.CancellationTokenSource.IsCancellationRequested)
Yes, because if the session was disposed you wouldn't need to return a CollectionItemResult.Error

2025-01-16 22:10 UTC, TalZaccai commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
- I think that only 1 client should get a result of 1, this happens do to the thread-unsafety in ClientCommands (see my comment there). 
- That's a good find - please let me know if you need any help here, this should be fixed promptly as it corrupts the data.

2025-01-16 22:11 UTC, TalZaccai requested changes
Thanks! Please see remaining comments :)

2025-01-16 22:22 UTC, badrishc commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
> Another interesting things I found is there is an issue with the list push command where if we push multiple items in then somehow all items values are just the same as last item's value. I will find the root cause and fix it as part of a separate PR
> 
> ```cs
> for (int i = 0; i < 20; i++)
> {
>     addTasks.Add(Task.Run(() => redis.GetDatabase(0).ListLeftPush(key, $"{value}{i}")));
> }
> await Task.Delay(1000)
> var resultInScreenshot = db.ListRange(key).Select(x => (string)x).ToArray();
> ```

This is a bug in your client code, not the server. You need to capture the `i` values correctly - something like this:

```cs
            for (int i = 0; i < 20; i++)
            {
                var _i = i;
                addTasks.Add(Task.Run(() => redis.GetDatabase(0).ListLeftPush(key, $"{value}{_i}")));
            }
```

2025-01-17 08:12 UTC, Vijay-Nirmal commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
@badrishc Ohh yaa, a rookie mistake from my end

2025-01-23 20:18 UTC, TalZaccai commented
Hey @Vijay-Nirmal! Any updates on the open comments here? :)

2025-01-23 20:26 UTC, Vijay-Nirmal commented
@TalZaccai Will work on it this weekend

2025-01-25 12:36 UTC, Vijay-Nirmal commented on libs/resources/RespCommandsDocs.json
> +        "Command": "CLIENT_UNBLOCK",
Done, Same JSON as before

2025-01-25 12:37 UTC, Vijay-Nirmal commented on libs/server/Resp/ClientCommands.cs
> +                while (!RespWriteUtils.WriteInteger(1, ref dcurr, dend))
Done. Nice proper design, better than mine :)

2025-01-25 12:41 UTC, Vijay-Nirmal commented on libs/server/Objects/ItemBroker/CollectionItemBroker.cs
> +            catch (OperationCanceledException) when (observer.CancellationTokenSource.IsCancellationRequested)
Done. With the change in the design, I reverted this code in this file

2025-01-25 12:41 UTC, Vijay-Nirmal commented on test/Garnet.test/RespTests.cs
> +        public async Task ClientUnblockMultipleAttemptsTest(string mode)
Done. With the new design, concurrent unblocking works as expected

2025-01-25 12:42 UTC, Vijay-Nirmal commented
@TalZaccai Fixed all review comments, sorry for the delay

2025-01-28 01:07 UTC, TalZaccai commented on libs/server/Resp/ClientCommands.cs
> +                while (!RespWriteUtils.WriteInteger(1, ref dcurr, dend))
Very nice! Glad I could help :)

2025-01-28 01:09 UTC, TalZaccai approved these changes
LGTM! Nice work!

2025-01-28 01:32 UTC, merged